title: arzumy md
tagline: short notes on small discoveries
production_url: http://ar.zu.my
author:
  name: Arzumy MD
  email: hello@ar.zu.my
meta:
  description: Arzumy is prolific CTO with over 12 years of experience. He has led engineering teams in a wide range of industries from 020, Fitness, Fintech, and e-Commerce to Digital Media and Mobile Communication.

highlighter: rogue
permalink: /:title
markdown: kramdown

content:
  talks:
    -
      date: 27 Jun 2015
      url: "https://academy.mymagic.my/events/event/product-management-workshop-series/"
      title: "MaGIC Academy - Product Management Series Workshop"
    -
      date: 07 Feb 2015
      url: "https://www.youtube.com/watch?v=ZpHH4rBP-S0"
      title: "MaGIC Academy - You Have An Idea? Great! Now What Are You Gonna Do About It"
    -
      date: 15 Oct 2014
      url: "https://www.youtube.com/watch?v=LiotgJQAz7E"
      title: "MSA Launch 2014 - MVP Prototyping In An Agile Environment – Ship Product Fast!"
    -
      date: 25 Sep 2013
      url: "http://www.ustream.tv/recorded/39221149"
      title: "WebcampKL Koko Crunch - Cash Payment in Malaysia"
    -
      date: 25 Sep 2013
      url: "http://www.ustream.tv/recorded/39221620"
      title: "WebcampKL Koko Crunch - Q&A Session"
    -
      date: 25 Aug 2012
      url: "https://www.youtube.com/watch?v=3q5UQ4N5hy0"
      title: "Ruby on Rails Malaysia Meetup - How We Deploy SAYS.com (unedited Google Hangout)"
    -
      date: 28 Sep 2011
      url: "http://webcamp.my/2011/10/arzumy-md-%E2%80%94-i-paul-the-octopus/"
      title: "WebCamp Neun: WCKL All-Stars - “I, Paul the Octopus”"
    -
      date: 27 Oct 2010
      url: "http://www.slideshare.net/arzumy/webcampkl-9-30second-tips-to-happiness-16-apps-in-8-minutes"
      title: "WebCampKL 9 - 30-second Tips To Happiness. 16 Apps In 8 Minutes"
    -
      date: 24 Feb 2009
      url: "http://www.slideshare.net/arzumy/ruby-on-rails-kickass"
      title: "MDeC Preseed Meetup - Ruby on Rails Kick-ass"
  news:
    -
      date: 27 Jul 2015
      url: "https://www.digitalnewsasia.com/node/45031"
      title: "Joel Neoh’s funding strategy to maximize equity"
    -
      date: 25 May 2014
      url: "https://www.youtube.com/watch?v=IE85QZPTOxQ"
      title: "AlphaStartups | Pre-Accelerator"
    -
      date: 23 Apr 2014
      url: "http://www.digitalnewsasia.com/sizzle-fizzle/taking-paper-out-of-the-billing-equation-with-billplz"
      title: "Taking paper out of the billing equation with Billplz"
    -
      date: 23 Jul 2013
      url: "http://e27.co/2013/07/23/aws-strengthens-commitment-to-sea-as-tech-startup-growth-increases/"
      title: "e27: AWS strengthens commitment to SEA as tech startup growth increases"
    -
      date: 12 Jan 2012
      url: "http://bfm.my/lifehacks.html"
      title: "BFM 89.9: The Business Station - Lifehacks"
    -
      date: 28 Sep 2011
      url: "http://www.bfm.my/techtalk_hackweekday2011.html"
      title: "BFM 89.9: The Business Station - HackWEEKDAY 2011"
    -
      date: 01 Sep 2005
      url: "http://www.nib.com.my/archives/text/view/9426915?pos=3&hide_header=1&resultset=nstpec%3Awww/cross-search/search.php%3A_1355414435%3Aresultset"
      title: "New Straits Times: Computimes - Hacking competition winners"
